[[constraint]]
    name = "github.com/waveywaves/helm-kelp"
    version = "0.1"

[[constraint]]
    name = "github.com/spf13/cobra"
    version = "0.0.5"

[prune]
    go-tests = true
    unused-packages = true

required = ["sigs.k8s.io/kustomize/v3"]
